language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
  - wget https://raw.githubusercontent.com/simonjbeaumont/ocaml-travis-coveralls/master/travis-coveralls.sh
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y supercollider
script: PACKAGE=osc bash -ex .travis-opam.sh && bash -ex travis-coveralls.sh
env:
  - OCAML_VERSION=4.02
  - OCAML_VERSION=4.02 DEPOPTS=lwt
