language: c
script: bash -ex .travis-ci.sh
env:
  - OCAML_VERSION=4.00.1 INSTALL_LWT=0
  - OCAML_VERSION=4.00.1 INSTALL_LWT=1
  - OCAML_VERSION=4.01.0 INSTALL_LWT=0
  - OCAML_VERSION=4.01.0 INSTALL_LWT=1
  - OCAML_VERSION=4.02.1 INSTALL_LWT=0
  - OCAML_VERSION=4.02.1 INSTALL_LWT=1
